[package]
name = "avalanche-rs"
version = "0.0.1"
authors = ["tbrunain <t.brunain@protonmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
